//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilesAnalyzer.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDBFile
    {
        public long Id { get; set; }
        public System.Guid Guid { get; set; }
        public string OriginalName { get; set; }
        public string ServerName { get; set; }
        public int Size { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Author { get; set; }
        public string Extension { get; set; }
        public bool IsDeleted { get; set; }
    }
}
